service:
  name: serverless-myplaces-app

plugins:
  - serverless-webpack
  - serverless-iam-roles-per-function
  - serverless-reqvalidator-plugin
  - serverless-aws-documentation
  - serverless-plugin-tracing

provider:
  name: aws
  runtime: nodejs12.x

  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}

  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    PROJECT_NAME: serverless-myplaces-app
    PLACE_TABLE: place-pembeweb-backend-table-${self:provider.stage}
    BUCKET_NAME: place-pembeweb-bucket-${self:provider.stage}

  tracing:
    lambda: true
    apiGateway: true

  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    documentation:
      api:
        info:
          version: '1.0.0'
          title: Places API
          description: Serverless My Places application
      models:
        - name: CreatePlaceRequest
          contentType: 'application/json'
          schema: ${file(models/PlaceItem.json)}
        - name: UpdatePlaceRequest
          contentType: 'application/json'
          schema: ${file(models/PlaceUpdate.json)}

functions:
  Auth:
    handler: src/lambda/auth/auth0Authorizer.handler

  GetPlaces:
    handler: src/lambda/http/getPlaces.handler
    events:
      - http:
          method: get
          path: places
          cors: true
          authorizer: Auth
    iamRoleStatementsName: ${self:provider.environment.PROJECT_NAME}-getplace-${self:provider.stage}
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Query
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.PLACE_TABLE}

  CreatePlace:
    handler: src/lambda/http/createPlace.handler
    events:
      - http:
          method: post
          path: places
          cors: true
          authorizer: Auth
          documentation:
            summary: 'Create a new item'
            description: 'Create a new item'
            requestModels:
              'application/json': CreatePlaceRequest
          reqValidatorName: onlyBody
    iamRoleStatementsName: ${self:provider.environment.PROJECT_NAME}-createplace-${self:provider.stage}
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.PLACE_TABLE}

  UpdatePlace:
    handler: src/lambda/http/updatePlace.handler
    events:
      - http:
          method: patch
          path: places/{placeId}
          cors: true
          authorizer: Auth
          documentation:
            summary: 'Update an item'
            description: 'Update an item'
            requestModels:
              'application/json': UpdatePlaceRequest
          reqValidatorName: onlyBody
    iamRoleStatementsName: ${self:provider.environment.PROJECT_NAME}-updateplace-${self:provider.stage}
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:UpdateItem
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.PLACE_TABLE}

  DeletePlace:
    handler: src/lambda/http/deletePlace.handler
    events:
      - http:
          method: delete
          path: places/{placeId}
          cors: true
          authorizer: Auth
    iamRoleStatementsName: ${self:provider.environment.PROJECT_NAME}-deleteplace-${self:provider.stage}
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:DeleteItem
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.PLACE_TABLE}

  GenerateUploadUrl:
    handler: src/lambda/http/generateUploadUrl.handler
    events:
      - http:
          method: post
          path: places/{placeId}/attachment
          cors: true
          authorizer: Auth
    iamRoleStatementsName: ${self:provider.environment.PROJECT_NAME}-s3upload-${self:provider.stage}
    iamRoleStatements:
      - Effect: Allow
        Action:
          - s3:*
        Resource: arn:aws:s3:::${self:provider.environment.BUCKET_NAME}/*

resources:
  Resources:
    PlacesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: placeId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: placeId
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.PLACE_TABLE}
    onlyBody:
      Type: 'AWS::ApiGateway::RequestValidator'
      Properties:
        Name: 'only-body'
        RestApiId:
          Ref: ApiGatewayRestApi
        ValidateRequestBody: true
        ValidateRequestParameters: false

    AttachmentsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.BUCKET_NAME}
        CorsConfiguration:
          CorsRules:
            - AllowedOrigins:
                - '*'
              AllowedHeaders:
                - '*'
              AllowedMethods:
                - GET
                - PUT
                - POST
                - DELETE
                - HEAD
              MaxAge: 3000

    BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        PolicyDocument:
          Id: MyPolicy
          Version: '2012-10-17'
          Statement:
            - Sid: PublicReadForGetBucketObjects
              Effect: Allow
              Principal: '*'
              Action: 's3:GetObject'
              Resource: 'arn:aws:s3:::${self:provider.environment.BUCKET_NAME}/*'
        Bucket: !Ref AttachmentsBucket
